name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 25.1
          - 25.3
          - 26.1
          - 26.3
          - snapshot
    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - uses: actions/checkout@v1
    - name: Get Markdown Mode
      run: curl -O https://raw.githubusercontent.com/jrblevin/markdown-mode/master/markdown-mode.el
    - name: Byte compile
      # NOTE Only Emacs 26.1+ honor byte-compile-error-on-warn
      run: emacs -Q --batch -L . --eval "(setq byte-compile-error-on-warn t)" -f batch-byte-compile mdcx.el
